name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Package FastAPI app
      run: |
        zip -r fastapi_app.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: fastapi_app
        path: fastapi_app.zip
