name: Deploy App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: fastapi_app

    - name: Unzip FastAPI app
      run: |
        unzip fastapi_app.zip -d app

    - name: Login via Azure CLI
      run: |
        az cloud set -n azurecloud
        az login --service-principal --username "583ff8fe-7b92-44cd-aa9f-f62c8af750b1" --password "sJj8Q~MGJGaFtynOAGqR8P2CvQHbyFp6oEDgpbsg" --tenant "8e5c9539-0a3e-4a96-b90e-0586ea2533de"
        
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: brainapis.azurecr.io
        username: "583ff8fe-7b92-44cd-aa9f-f62c8af750b1"
        password: "sJj8Q~MGJGaFtynOAGqR8P2CvQHbyFp6oEDgpbsg"
     
    - name: Build and push container image to registry 
      run: |
        docker build . -t brainapis.azurecr.io/fastapi-cd:${{ github.sha }}
        docker push brainapis.azurecr.io/fastapi-cd:${{ github.sha }}
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'allibrainapp'
        images: 'brainapis.azurecr.io/fastapi-cd:${{ github.sha }}'
        
    - name: Azure logout
      run: |
        az logout
