name: Azure Function App CI/CD with Container Registry

on:
  push:
    branches:
      - one
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_4d0f68854ca742d39760f916e0d6f72d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c1d5c185cd144fa4ae37e8d1d3bb019b }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: docker.io/${{ secrets.AzureAppService_ContainerUsername_4d0f68854ca742d39760f916e0d6f72d }}/mypythonfunctionapp:latest

    - name: Azure Login
      uses: docker/login-action@v1
      with:
        registry: https://brainapis.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d0f68854ca742d39760f916e0d6f72d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c1d5c185cd144fa4ae37e8d1d3bb019b }}


    - name: Deploy to Function App
      uses: Azure/functions-action@v1
      with:
        app-name: allibrain
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5072362e03444bfa94ebaad6f8a9d09e }}
        images: docker.io/${{ secrets.AzureAppService_ContainerUsername_4d0f68854ca742d39760f916e0d6f72d }}/mypythonfunctionapp:latest
