name: Azure Function App CI/CD with Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - one

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CLIENTID }}
          password: ${{ secrets.CLIENTSECRET }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: docker.io/${{ secrets.CLIENTID }}/mypythonfunctionapp:latest
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Deploy to Function App
        uses: Azure/functions-action@v1
        with:
          app-name: <function-app-name>
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          slot-name: <optional-slot-name>
          images: docker.io/${{ secrets.CLIENTID }}/mypythonfunctionapp:latest
