name: Azure Function App CI/CD with Container Registry

on:
  push:
    branches:
      - one
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: docker.io/brainapis/mypythonfunctionapp:latest
          username: 'brainapis'
          password: 'sWxKTzXcRe6huP//MZWr2xwmjkuCJvEBkAzOTQukRI+ACRDncYkA'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      
      - name: Deploy to Function App
        uses: Azure/functions-action@v1
        with:
          app-name: allibrain
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: docker.io/brainapis/mypythonfunctionapp:latest
