name: Deploy 1

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login via Azure CLI
      run: |
        az cloud set -n azurecloud
        az login --service-principal --username "583ff8fe-7b92-44cd-aa9f-f62c8af750b1" --password "sJj8Q~MGJGaFtynOAGqR8P2CvQHbyFp6oEDgpbsg" --tenant "8e5c9539-0a3e-4a96-b90e-0586ea2533de"

    - name: Install Azure Functions Core Tools
      uses: Azure/functions-action@v1
      with:
        app-name: allibrain
        appSettings: <publishData><publishProfile profileName="allibrain - Web Deploy" publishMethod="MSDeploy" publishUrl="allibrain.scm.azurewebsites.net:443" msdeploySite="allibrain" userName="$allibrain" userPWD="w2HlWnQCZ39HswMFpPG1kxJavcfdN2WfLPPzKruurJXRSd5zzAaPpXjy8Hv9" destinationAppUrl="https://allibrain.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="allibrain - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-077.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="allibrain\$allibrain" userPWD="w2HlWnQCZ39HswMFpPG1kxJavcfdN2WfLPPzKruurJXRSd5zzAaPpXjy8Hv9" destinationAppUrl="https://allibrain.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="allibrain - Zip Deploy" publishMethod="ZipDeploy" publishUrl="allibrain.scm.azurewebsites.net:443" userName="$allibrain" userPWD="w2HlWnQCZ39HswMFpPG1kxJavcfdN2WfLPPzKruurJXRSd5zzAaPpXjy8Hv9" destinationAppUrl="https://allibrain.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="allibrain - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-077dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="allibrain\$allibrain" userPWD="w2HlWnQCZ39HswMFpPG1kxJavcfdN2WfLPPzKruurJXRSd5zzAaPpXjy8Hv9" destinationAppUrl="https://allibrain.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and deploy function app
      run: |
        func azure functionapp publish allibrain --python
